image: node:18.17.1

stages:
- build
- test
- deploy

build:
  image: docker:latest
  stage: build

  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

test:
  stage: test
  script:
    - npm install eslint
    - node_modules/eslint/bin/eslint.js .

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"


